FROM debezium/connect:2.4

# Ścieżki gdzie Connect szuka pluginów
ENV CONNECT_PLUGIN_PATH="/usr/share/java,/kafka/connect/jars"

# Kopiujemy JAR-y do istniejącej lokalizacji, która jest już wewnętrznie dostępna i zapisana w ścieżce pluginów
COPY etc/kafka/connect/jars /kafka/connect/jars