FROM confluentinc/cp-kafka:7.5.0

USER root

# Instalujemy dodatkowe narzędzia z pakietu
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:7.5.0 && \
    chmod -R a+rwX /usr/share/java

# Upewniamy się, że PATH zawiera potrzebne narzędzia (są w image)
ENV PATH="$PATH:/usr/bin"
