services:
  postgres:
    image: debezium/postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: >
      postgres
        -c wal_level=logical
        -c max_replication_slots=4
        -c max_wal_senders=4
        -c max_worker_processes=4
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      # 1) Init-script wykona się tylko przy pierwszym starcie (pusty wolumen pgdata)
      - ./database/initdb:/docker-entrypoint-initdb.d:ro,z
      # 2) Nazwany wolumen na dane Postgresa
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      FLASK_PORT: ${FLASK_PORT}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_HOST: ${FLASK_HOST}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:${KAFKA_PORT}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - "${SCHEMA_REGISTRY_PORT}:${SCHEMA_REGISTRY_PORT}"

  connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: connect
    depends_on:
      - kafka
      - schema-registry
      - postgres
    ports:
      - "${CONNECTOR_PORT}:${CONNECTOR_PORT}"
    environment:
      BOOTSTRAP_SERVERS: "kafka:${KAFKA_PORT}"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
      KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:${SCHEMA_REGISTRY_PORT}"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:${SCHEMA_REGISTRY_PORT}"
      CONNECT_PLUGIN_PATH: "/kafka/connect,/usr/share/java,/etc/kafka-connect/jars"
    # volumes:
      # Tu muszą trafić JAR-y Debezium i Avro Convertera
      # - ./etc/kafka/connect/jars:/etc/kafka-connect/jars
    restart: unless-stopped

  connector-registrator:
    build:
      context: .
      dockerfile: Dockerfile.connector-registrator
    container_name: connector-registrator
    depends_on:
      - connect
    environment:
      CONNECTOR_PORT: ${CONNECTOR_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER_NAME: ${DB_SERVER_NAME}
      DB_TABLE: ${DB_TABLE}
      DB_SLOT_NAME: ${DB_SLOT_NAME}
      DB_TOPIC_PREFIX: ${DB_TOPIC_PREFIX}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}

  kafka-tools:
    # image: confluentinc/cp-schema-registry:7.5.0
    build:
      context: .
      dockerfile: Dockerfile.kafka-tools
    container_name: kafka-tools
    depends_on:
      - kafka
      - schema-registry
    entrypoint: ["sh","-c","tail -f /dev/null"]

  generator:
    build: .
    container_name: generator
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["python", "main.py"]

# Definicja nazwanego wolumenu (tylko ten jeden!)
volumes:
  pgdata:
