# services:
#   app:
#     build: .
#     container_name: bgd_lab0
#     environment:
#       DB_USERNAME: ${DB_USERNAME}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_HOST: ${DB_HOST}
#       DB_PORT: ${DB_PORT}
#       DB_NAME: ${DB_NAME}
#     ports:
#       - "5433:5433" # Map host port 5433 to container port 5432
#     volumes:
#       - ./data:/app/data
#     command: ["python", "__main__.py"]