CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'replicator_pw';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO replicator;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO replicator;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO replicator;
